[General]
Name = PLT Focus
Class = 0x000404
DiscoverableTimeout = 0
AlwaysPairable = true
PairableTimeout = 0
ControllerMode = bredr
FastConnectable = true
JustWorksRepairing = always

[Policy]
AutoEnable = true
ReconnectAttempts = 7
ReconnectIntervals = 1,2,4,8,16,32,64

